sudo: required

services:
  - docker

# https://github.com/prometheus/node_exporter/releases
env:
  matrix:
    - ARCH=arm   QEMU=qemu-arm-static     BASE_IMAGE=arm32v7/debian:jessie-slim  BIN_SOURCE=v0.17.0-rc.0/node_exporter-0.17.0-rc.0.linux-armv7
    - ARCH=arm64 QEMU=qemu-aarch64-static BASE_IMAGE=arm64v8/debian:jessie-slim  BIN_SOURCE=v0.17.0-rc.0/node_exporter-0.17.0-rc.0.linux-arm64
    - ARCH=amd64 QEMU=qemu-fake-static    BASE_IMAGE=amd64/debian:jessie-slim    BIN_SOURCE=v0.17.0-rc.0/node_exporter-0.17.0-rc.0.linux-amd64

script:
  - ./travis-build.sh
  - >
    if [ -n "$TRAVIS_TAG" ]; then
      travis_retry timeout 5m docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      ./travis-deploy.sh
    fi
